name: 'Semantic Labeler'
description: Labels the PR using semantic release conventional commits
inputs:
  token:
    description: Github authentication token
    default: github.token
  tag-format:
    description: The semantic release tag format
    required: false

outputs:
  is-release:
    description: Whether there is a release or not
  release-type:
    description: The release type
  release-name:
    description: The release name
  release-notes:
    description: The release notes
  
  
runs:
  using: 'node16'
  main: 'release/index.js'