name: 'Semantic Labeler'
description: Labels the PR using semantic release conventional commits
inputs:
  token:
    description: Github authentication token
    default: github.token

outputs:
  is-release:
    description: Whether there is a release or not
  release-type:
    description: The release type
  channel:
    description: The release channel
  release-notes:
    description: The release notes
  
runs:
  using: 'node16'
  main: 'release/index.js'