name: Semantic Labeler

on:
  pull_request:
    types: [synchronize, opened]

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Need to build this action to run it bellow
    - name: Setup node v16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: yarn
      name: Install dependencies
    - run: yarn build
      name: Build local action
    - name: Semantic Labeler
      uses: ./
      with:
        token: ${{secrets.GITHUB_TOKEN}}